sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t Machindra220/docker-repo -f Dockerfile.dev .

script:
  - docker run -e CI=true Machindra220/docker-repo npm run test -- --coverage
