sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t machindra220/docker-repo -f Dockerfile.dev .

script:
  - docker run machindra220/docker-repo npm run test -- --coverage
